branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: Investigation-Frontend-env
environment-defaults:
  Investigation-Frontend-env:
    branch: master
    repository: angular-client
global:
  application_name: investigation-frontend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
