#!/bin/bash

echo "Use custom hook to build image:"
echo Configuration: $CONFIGURATION
echo Image name: $IMAGE_NAME
echo Docker file path: $DOCKERFILE_PATH

docker build --build-arg CONFIGURATION=$CONFIGURATION -f $DOCKERFILE_PATH -t $IMAGE_NAME
